M48
; DRILL file {KiCad (6.0.6-0)} date 2022 September 01, Thursday 16:53:14
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-09-01T16:53:14+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X57.5Y-57.5
X57.5Y-142.5
X100.0Y-100.0
X142.5Y-57.5
X142.5Y-142.5
T0
M30
