M48
; DRILL file {KiCad (6.0.6-0)} date 2023 January 18, Wednesday 22:31:43
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-18T22:31:43+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X57.5Y-57.5
X57.5Y-142.5
X100.0Y-100.0
X142.5Y-57.5
X142.5Y-142.5
T0
M30
